repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        exclude: ^vendor/
      - id: check-yaml
        exclude: ^vendor/
      - id: check-json
        exclude: ^vendor/
      - id: end-of-file-fixer
        exclude: ^vendor/
      - id: trailing-whitespace
        exclude: ^vendor/
      - id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: ^vendor/

  - repo: https://github.com/golangci/golangci-lint.git
    rev: v2.2.2
    hooks:
      - id: golangci-lint
        args: [--fix]
        exclude: ^vendor/
      - id: golangci-lint-fmt
        exclude: ^vendor/
      - id: golangci-lint-full
        exclude: ^vendor/
