package llm

import (
	"context"
	"fmt"
	"strings"

	"github.com/openai/openai-go"
	openaioption "github.com/openai/openai-go/option"
)

// OpenAIGenerator Implemention OpenAI provider
type OpenAIGenerator struct {
	apiKey string
}

func NewOpenAIGenerator(apiKey string) *OpenAIGenerator {
	return &OpenAIGenerator{apiKey: apiKey}
}

func (g *OpenAIGenerator) GenerateCommitMessage(diff string) (string, error) {
	return generateOpenAICommitMessage(diff, g.apiKey)
}

func generateOpenAICommitMessage(diff, apiKey string) (string, error) {
	client := openai.NewClient(
		openaioption.WithAPIKey(apiKey),
	)
	ctx := context.Background()
	prompt := fmt.Sprintf("%s\n%s", llmPrompt, diff)

	chatCompletion, err := client.Chat.Completions.New(ctx, openai.ChatCompletionNewParams{
		Messages: openai.F([]openai.ChatCompletionMessageParamUnion{
			openai.UserMessage(prompt),
		}),
		Model: openai.F(openai.ChatModelGPT4o),
	})
	if err != nil {
		return "", fmt.Errorf("generating commit message: %w", err)
	}

	if len(chatCompletion.Choices) > 0 {
		return strings.TrimSpace(chatCompletion.Choices[0].Message.Content), nil
	}

	return "", fmt.Errorf("no commit message generated by OpenAI")
}
