package llm

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/openai/openai-go"
	openaioption "github.com/openai/openai-go/option"
)

// QwenGenerator Implemention Qwen provider
type QwenGenerator struct {
	apiKey string
}

func NewQwenGenerator(apiKey string) *QwenGenerator {
	return &QwenGenerator{apiKey: apiKey}
}

func (g *QwenGenerator) GenerateCommitMessage(diff string) (string, error) {
	return generateQwenCommitMessage(diff, g.apiKey, qwenModel, "https://dashscope.aliyuncs.com/compatible-mode/v1/")
}

// ModelscopeGenerator Implemention Modelscope provider
type ModelscopeGenerator struct {
	apiKey    string
	modelName string
}

func NewModelscopeGenerator(apiKey, modelName string) *ModelscopeGenerator {
	return &ModelscopeGenerator{apiKey: apiKey, modelName: modelName}
}

func (g *ModelscopeGenerator) GenerateCommitMessage(diff string) (string, error) {
	return generateQwenCommitMessage(diff, g.apiKey, g.modelName, "https://api-inference.modelscope.cn/v1/")
}

type SelfHostedGenerator struct {
	apiKey    string
	endpoint  string
	modelName string
}

func NewSelfHostedGenerator(apiKey, endpoint, modelName string) *SelfHostedGenerator {
	return &SelfHostedGenerator{apiKey: apiKey, endpoint: endpoint, modelName: modelName}
}

func (g *SelfHostedGenerator) GenerateCommitMessage(diff string) (string, error) {
	return generateQwenCommitMessage(diff, g.apiKey, g.modelName, fmt.Sprintf("%s/v1/", g.endpoint))
}

func generateQwenCommitMessage(diff, apiKey string, modelName string, baseURL string) (string, error) {
	apiKey = strings.TrimSpace(apiKey)
	if apiKey == "" {
		apiKey = os.Getenv("DASHSCOPE_API_KEY")
	}

	if apiKey == "" {
		return "", fmt.Errorf("API key is empty: please provide an API key via configuration or DASHSCOPE_API_KEY environment variable")
	}

	client := openai.NewClient(
		openaioption.WithAPIKey(apiKey),
		openaioption.WithBaseURL(baseURL),
	)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	prompt := fmt.Sprintf("%s\n%s", llmPrompt, diff)

	chatCompletion, err := client.Chat.Completions.New(ctx, openai.ChatCompletionNewParams{
		Messages: openai.F([]openai.ChatCompletionMessageParamUnion{
			openai.UserMessage(prompt),
		}),
		Model: openai.F(modelName),
	})
	if err != nil {
		return "", fmt.Errorf("generating commit message: %w", err)
	}

	if len(chatCompletion.Choices) > 0 {
		return strings.TrimSpace(chatCompletion.Choices[0].Message.Content), nil
	}

	return "", fmt.Errorf("no commit message generated by Qwen")
}
